[tool.poetry]
name = "auralflow"
version = "0.1.1"
description = "A lightweight music source separation toolkit."
authors = ["Kian Zohoury <kzohoury@berkeley.edu>"]
license = "MIT"
packages = [{include = "auralflow"}]

[tool.poetry.dependencies]
python = "^3.7.1"

[tool.poetry.dev-dependencies]
auralflow = "^0.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

