[tool.poetry]
name = "auralflow"
version = "0.1.2"
description = "A lightweight music source separation toolkit."
authors = ["Kian Zohoury <kzohoury@berkeley.edu>"]
license = "MIT"
packages = [{include = "auralflow"}]

[tool.poetry.dependencies]
python = ">= 3.9.1 < 3.11"
llvmlite = "^0.38.1"
librosa = "^0.9.1"
numpy = "^1.22.4"
protobuf = "3.20.1"
tensorboard = "^2.9.0"
matplotlib = "^3.5.2"
tqdm = "^4.64.0"
asteroid = "^0.5.2"
torch = "1.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

