[tool.poetry]
name = "auralflow"
version = "0.1.0"
description = "A lightweight music source separation toolkit."
authors = ["Kian Zohoury <kzohoury@berkeley.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.7.1"
pendulum = "^2.1.2"
torch = "^1.11.0"
torchaudio = "^0.11.0"
jupyter = "^1.0.0"
fast-bss-eval = "^0.1.3"
librosa = "^0.9.1"
asteroid = "^0.5.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
