[tool.poetry]
name = "auralflow"
version = "0.1.2"
description = "A lightweight music source separation toolkit."
authors = ["Kian Zohoury <kzohoury@berkeley.edu>"]
license = "MIT"
packages = [{include = "auralflow"}]

[tool.poetry.dependencies]
python = ">= 3.7.11 < 3.11"
torch = "1.10.0"
librosa = "^0.9.1"
numpy = "1.21.0"
asteroid = "^0.5.2"
tensorboard = "^2.9.0"
protobuf = "3.20.0"
pytorch-lightning = "1.4.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
