[tool.poetry]
name = "auralflow"
version = "0.1.2"
description = "A lightweight music source separation toolkit."
authors = ["Kian Zohoury <kzohoury@berkeley.edu>"]
readme = "README.md"
license = "MIT"
packages = [{include = "auralflow"}]

[tool.poetry.dependencies]
python = ">= 3.7.11 < 3.11"
torch = "1.10.0"
librosa = "^0.9.1"
numpy = "1.21.0"
asteroid = "^0.5.2"
tensorboard = "^2.9.0"
protobuf = "3.20.0"
pytorch-lightning = "1.4.8"
django-livereload = "^1.7"
livereload = "^2.6.3"
sphinx-reload = "^0.2.0"
matplotlib = "^3.5.2"
prettytable = "^3.3.0"
sphinx-autodoc-typehints = "^1.18.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
