# Dataset parameters.
data:
  # targets:
  #   Target sources to separate. Pass in one or more sources as a list.
  # num-channels:
  #   Number of channels (mono = 1, stereo = 2). Default: 1.
  # sample-rate:
  #   Sampling rate of the audio files.
  # num-fft:
  #   Number of STFT bins to create.
  # window-size:
  #   Window size of the STFT window function.
  # hop-length:
  #   Hop length of the STFT window function.
  # sample-length:
  #   Duration of the sampled audio clips.
  # backend:
  #   Backend audio framework for loading audio files.
  targets: [vocals, bass, drums]
  num-channels: 1
  sample-rate: 44100
  num-fft: 1024
  window-size: 1024
  hop-length: 768
  sample-length: 3
  audio-format: wav
  backend: soundfile
