my_session:
  session-id: my_session
  location: /Users/Kian/Desktop/Auralate/my_session
  date-created: 18/04/2022 14:29:41
  models:
  - my_unet
second_session:
  session-id: second_session
  location: /Users/Kian/Desktop/Auralate/second_session
  date-created: 17/04/2022 21:32:08
  models:
  - new_model
current:
  session-id: my_session
  location: /Users/Kian/Desktop/Auralate/my_session
