new_session:
  session-id: new_session
  location: /Users/Kian/Desktop/auralflow/new_session
  date-created: 26/04/2022 13:03:04
  models:
  - my_model
current:
  session-id: new_session
  location: /Users/Kian/Desktop/auralflow/new_session
